name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.versions.outputs.version }}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from pack.mcmeta
        id: versions
        run: |
          VERSION=$(grep -o -m 1 -E "(v[0-9]+\.){1}[0-9]+(\.[0-9]+)?" pack.mcmeta)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check versions
        run: |
          OLD_VER=$(git tag --list 'v*' --sort=-v:refname | head -n 1 | sed -e "s/v//")
          NEW_VER=$(echo ${{ steps.versions.outputs.version }} | sed -e "s/v//")

          if [ 1 -eq "$(echo "${OLD_VER} >= ${NEW_VER}" | bc)" ]; then
            echo "バージョン番号が正しくありません。"
            exit 1
          fi

      - name: Remove unnecessary files
        run: |
          rm -rf .github
          rm -rf renovate.json

      - name: Create ZIP file
        run: |
          zip -r Fantaisie-ResourcePack.zip *

      - uses: actions/upload-artifact@v4
        with:
          name: zip_file
          path: Fantaisie-ResourcePack.zip

  release:
    name: Release
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ZIP file
        uses: actions/download-artifact@v4
        with:
          name: zip_file

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: Fantaisie-ResourcePack.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.build.outputs.version }}
