name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.versions.outputs.version }}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from pack.mcmeta
        id: versions
        run: |
          VERSION=$(grep -o -m 1 -E "(v[0-9]+\.){1}[0-9]+(\.[0-9]+)?" pack.mcmeta)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version=$VERSION"

      - name: Check if version already exists
        id: check_version
        run: |
          EXISTING_TAG=$(git tag -l "${{ steps.versions.outputs.version }}")
          if [ -n "$EXISTING_TAG" ]; then
            echo "Version $EXISTING_TAG already exists. Exiting..."
            exit 1
          fi

      - name: Remove unnecessary files
        run: |
          rm -rf .github
          rm -rf renovate.json

      - name: Create ZIP file
        run: |
          zip -r Fantaisie-ResourcePack.zip *

      - uses: actions/upload-artifact@v4
        with:
          name: zip_file
          path: Fantaisie-ResourcePack.zip

  release:
    name: Release
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ZIP file
        uses: actions/download-artifact@v4
        with:
          name: zip_file

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.build.outputs.version }}
          tag_name: ${{ needs.build.outputs.version }}
          files: Fantaisie-ResourcePack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ needs.build.outputs.version }}
